---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-vote
  namespace: persistent-k8-vapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-vote
  template:
    metadata:
      labels:
        app: redis-vote
    spec:
      containers:
      - name: redis-vote
        image: "terraformacrunir.azurecr.io/redis-hector:latest"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data     
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-vote