---
apiVersion: v1
kind: Service
metadata:
  name: db-vote
  namespace: persistent-k8-vapp
spec:
  selector:
    app: db-vote
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
