apiVersion: v1
kind: Service
metadata:
  name: result-frontend
  namespace: persistent-k8-vapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: result-frontend
